export default {
    GET_GENRES: 'GET_GENRES',
    GET_GENRES_SUCCESS: 'GET_GENRES_SUCCESS',
    GET_GENRES_FAILURE: 'GET_GENRES_SUCCESS',
    GET_MOVIES: 'GET_MOVIES',
    GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
    GET_MOVIES_FAILURE: 'GET_MOVIES_FAILURE'
};
